name: Trigger auto deployment for my-devweb-fe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ] # commit dev 就可以了
    paths:
    - '**'
    - '.github/workflows/my-devweb-fe-AutoDeployTrigger.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MYDEVWEBFE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYDEVWEBFE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYDEVWEBFE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: mydevwebcontainerregistry.azurecr.io
          registryUsername: ${{ secrets.MYDEVWEBFE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYDEVWEBFE_REGISTRY_PASSWORD }}
          containerAppName: my-devweb-fe
          resourceGroup: MyPersonalWebsite
          imageToBuild: mydevwebcontainerregistry.azurecr.io/my-devweb-fe:${{ github.sha }}
          buildArguments: |
            VITE_APP_ENV=${{ vars.VITE_APP_ENV }}
            VITE_API_BASE=${{ vars.VITE_API_BASE }}
            VITE_AUTH_BASE=${{ vars.VITE_AUTH_BASE }}
            VITE_GOOGLE_CLIENT_ID=${{ vars.VITE_GOOGLE_CLIENT_ID }}
            VITE_DISABLE_AUTH=${{ vars.VITE_DISABLE_AUTH }}
            VITE_SHOW_PRIVATE=${{ vars.VITE_SHOW_PRIVATE }}


